services:
  skynet:
    build: .
    container_name: skynet
    ports: 
      - "8000:8000" 
      - "8888:8888"
    volumes:
      - ./skynet:/app/skynet
      - ./game:/app/game
      - ./third_party:/app/third_party
      - ./proto:/app/proto
    tty: true
    stdin_open: true
    depends_on: 
      - mysql 
      - redis 
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: game
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data